package com.example.entity;

import java.time.LocalDateTime;
import java.util.List;

import com.example.entity.jobposting.SavedJob;
import com.example.entity.profile.Education;
import com.example.entity.profile.Experience;
import com.example.entity.profile.JobPreferences;
import com.example.entity.profile.JobSeekerPersonalInfo;
import com.example.entity.profile.SocialProfile;
import com.example.enums.Role;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.CascadeType;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Entity class representing a Job Seeker in the system. Maps to the "JobSeeker"
 * table in the database.
 */
@Entity
@Table(name = "JobSeeker")
public class JobSeeker {

	/**
	 * Primary key - Unique identifier for each JobSeeker. Auto-generated by the
	 * database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	/** Full name of the job seeker */
	private String fullName;

	/** Email address, used as a login identifier */
	private String email;

	/** Mobile phone number */
	private String mobileNumber;

	/** Password for authentication */
	private String password;

	/**
	 * Confirm password field used for validation during registration/update. Marked
	 * as @Transient to avoid persistence in the database.
	 */
	@Transient
	private String confirmPassword;

	// for Email verification

	private boolean isVerified;
	// To store OTP
	private String otp;
	// To store date&time for Otp expire
	private LocalDateTime otpGeneratedTime;
	
	
	//MObile number varification!..
	private String mobileOtp;	
	private LocalDateTime mobileOtpGeneratedTime;	
	private boolean isMobileVerified;


	// personalInfo
	@OneToOne(mappedBy = "jobSeeker", cascade = CascadeType.ALL)
	@JsonManagedReference
	private JobSeekerPersonalInfo personalInfo;

	// education
	@OneToMany(mappedBy = "jobSeeker", cascade = CascadeType.ALL)
	@JsonManagedReference
	private List<Education> educationList;

	// experience
	@OneToMany(mappedBy = "jobSeeker", cascade = CascadeType.ALL)
	@JsonManagedReference
	private List<Experience> experienceList;

	// skills
	@ElementCollection
	private List<String> skills;

	// social profile
	@OneToOne(mappedBy = "jobSeeker", cascade = CascadeType.ALL)
	@JsonManagedReference
	private SocialProfile socialProfile;

	// jobpreference
	@OneToOne(mappedBy = "jobSeeker", cascade = CascadeType.ALL)
	@JsonManagedReference
	private JobPreferences jobPrefeences;
	
	
	// saved job
	@OneToMany(mappedBy = "jobSeeker", cascade = CascadeType.ALL)
	private List<SavedJob> savedJobs;
	
	// role of user
	@Enumerated(EnumType.STRING)
	private Role role;

	public JobSeeker() {
		super();
		// TODO Auto-generated constructor stub
	}

	public JobSeeker(int id, String fullName, String email, String mobileNumber, String password,
			String confirmPassword, JobSeekerPersonalInfo personalInfo, List<Education> educationList,
			List<Experience> experienceList, List<String> skills, SocialProfile socialProfile,
			JobPreferences jobPrefeences, boolean isVerified, String otp, LocalDateTime otpGeneratedTime,String mobileOtp,
			LocalDateTime mobileOtpGeneratedTime,boolean isMobileVerified , List<SavedJob> savedJobs
			, Role role) {
		super();
		this.id = id;
		this.fullName = fullName;
		this.email = email;
		this.mobileNumber = mobileNumber;
		this.password = password;
		this.confirmPassword = confirmPassword;
		this.personalInfo = personalInfo;
		this.educationList = educationList;
		this.experienceList = experienceList;
		this.skills = skills;
		this.socialProfile = socialProfile;
		this.jobPrefeences = jobPrefeences;
		this.isVerified = isVerified;
		this.otp = otp;
		this.savedJobs=savedJobs;
		this.role=role;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public JobSeekerPersonalInfo getPersonalInfo() {
		return personalInfo;
	}

	public void setPersonalInfo(JobSeekerPersonalInfo personalInfo) {
		this.personalInfo = personalInfo;
	}

	public List<Education> getEducationList() {
		return educationList;
	}

	public void setEducationList(List<Education> educationList) {
		this.educationList = educationList;
	}

	public List<Experience> getExperienceList() {
		return experienceList;
	}

	public void setExperienceList(List<Experience> experienceList) {
		this.experienceList = experienceList;
	}

	public List<String> getSkills() {
		return skills;
	}

	public void setSkills(List<String> skills) {
		this.skills = skills;
	}

	public SocialProfile getSocialProfile() {
		return socialProfile;
	}

	public void setSocialProfile(SocialProfile socialProfile) {
		this.socialProfile = socialProfile;
	}

	public JobPreferences getJobPrefeences() {
		return jobPrefeences;
	}

	public void setJobPrefeences(JobPreferences jobPrefeences) {
		this.jobPrefeences = jobPrefeences;
	}

	public boolean isVerified() {
		return isVerified;
	}

	public void setVerified(boolean isVerified) {
		this.isVerified = isVerified;
	}

	public String getOtp() {
		return otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	public LocalDateTime getOtpGeneratedTime() {
		return otpGeneratedTime;
	}

	public void setOtpGeneratedTime(LocalDateTime otpGeneratedTime) {
		this.otpGeneratedTime = otpGeneratedTime;
	}

	public String getMobileOtp() {
		return mobileOtp;
	}

	public void setMobileOtp(String mobileOtp) {
		this.mobileOtp = mobileOtp;
	}

	public LocalDateTime getMobileOtpGeneratedTime() {
		return mobileOtpGeneratedTime;
	}

	public void setMobileOtpGeneratedTime(LocalDateTime mobileOtpGeneratedTime) {
		this.mobileOtpGeneratedTime = mobileOtpGeneratedTime;
	}

	public boolean isMobileVerified() {
		return isMobileVerified;
	}

	public void setMobileVerified(boolean isMobileVerified) {
		this.isMobileVerified = isMobileVerified;
	}

	public List<SavedJob> getSavedJobs() {
		return savedJobs;
	}

	public void setSavedJobs(List<SavedJob> savedJobs) {
		this.savedJobs = savedJobs;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}
	
	
	
	

	
}
