package com.example.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;

/**
 * Entity class representing a Job Seeker in the system.
 * Maps to the "JobSeeker" table in the database.
 */
@Entity
@Table(name = "JobSeeker")
public class JobSeeker {
	
	/**
	 * Primary key - Unique identifier for each JobSeeker.
	 * Auto-generated by the database.
	 */
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	/** Full name of the job seeker */
	private String fullName;
	
	
	/** Email address, used as a login identifier */
	private String email;
	
	/** Password for authentication */
	private String password;

	/**
	 * Confirm password field used for validation during registration/update.
	 * Marked as @Transient to avoid persistence in the database.
	 */
	@Transient
	private String confirmPassword;

	/** Mobile phone number */
	private String mobileNumber;
	
	/** Residential or mailing address */
	private String address;
	
	/** Gender of the job seeker */
	private String gender;
	
	/** Date of birth */
	private LocalDate dateOfBirth;

	/** Short summary or bio of the job seeker */
	private String profileSummary;
	
	/** Highest educational qualification attained */
	private String highestEducationQualification;
	
	/** Year of passing or graduation */
	private String yearOfPassing;
	
	/** Name of the college/university attended */
	private String collegeName;
	
	/** Skills possessed by the job seeker (comma separated) */
	private String skills;
	
	/** Number of years of professional experience */
	private int yearsOfExperience;
	
	/** URL link to the uploaded resume document */
	private String resumeUrl;
	
	/** URL of GitHub profile */
	private String githubProfileUrl;

	/** URL to the profile image */
	private String profileImageUrl;
	
	/** Preferred job location (city or region) */
	private String preferredJobLocation;
	
	/** Notice period required before joining a new job */
	private String noticePeriod;
	
	/** Current annual salary (CTC) in numeric form */
	private Double currentCtc;
	
	/** Expected annual salary (CTC) in numeric form */
	private Double expectedCtc;

	/** Indicates if the profile is complete or still in progress */
	private boolean profileComplete;

	/** Timestamp when the profile was created */
	private LocalDateTime createdAt;
	
	/** Timestamp when the profile was last updated */
	private LocalDateTime updatedAt;

	// Getter and Setter methods for each field

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	

	public String getFullName() {
		return fullName;
	}
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}

	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}

	public LocalDate getDateOfBirth() {
		return dateOfBirth;
	}
	public void setDateOfBirth(LocalDate dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getProfileSummary() {
		return profileSummary;
	}
	public void setProfileSummary(String profileSummary) {
		this.profileSummary = profileSummary;
	}

	public String getHighestEducationQualification() {
		return highestEducationQualification;
	}
	public void setHighestEducationQualification(String highestEducationQualification) {
		this.highestEducationQualification = highestEducationQualification;
	}

	public String getYearOfPassing() {
		return yearOfPassing;
	}
	public void setYearOfPassing(String yearOfPassing) {
		this.yearOfPassing = yearOfPassing;
	}

	public String getCollegeName() {
		return collegeName;
	}
	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	public String getSkills() {
		return skills;
	}
	public void setSkills(String skills) {
		this.skills = skills;
	}

	public int getYearsOfExperience() {
		return yearsOfExperience;
	}
	public void setYearsOfExperience(int yearsOfExperience) {
		this.yearsOfExperience = yearsOfExperience;
	}

	public String getResumeUrl() {
		return resumeUrl;
	}
	public void setResumeUrl(String resumeUrl) {
		this.resumeUrl = resumeUrl;
	}

	public String getGithubProfileUrl() {
		return githubProfileUrl;
	}
	public void setGithubProfileUrl(String githubProfileUrl) {
		this.githubProfileUrl = githubProfileUrl;
	}

	public String getProfileImageUrl() {
		return profileImageUrl;
	}
	public void setProfileImageUrl(String profileImageUrl) {
		this.profileImageUrl = profileImageUrl;
	}

	public String getPreferredJobLocation() {
		return preferredJobLocation;
	}
	public void setPreferredJobLocation(String preferredJobLocation) {
		this.preferredJobLocation = preferredJobLocation;
	}

	public String getNoticePeriod() {
		return noticePeriod;
	}
	public void setNoticePeriod(String noticePeriod) {
		this.noticePeriod = noticePeriod;
	}

	public Double getCurrentCtc() {
		return currentCtc;
	}
	public void setCurrentCtc(Double currentCtc) {
		this.currentCtc = currentCtc;
	}

	public Double getExpectedCtc() {
		return expectedCtc;
	}
	public void setExpectedCtc(Double expectedCtc) {
		this.expectedCtc = expectedCtc;
	}

	public boolean isProfileComplete() {
		return profileComplete;
	}
	public void setProfileComplete(boolean profileComplete) {
		this.profileComplete = profileComplete;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * Default no-argument constructor.
	 */
	public JobSeeker() {
		super();
	}
	public JobSeeker(int id, String fullName, String email, String password, String confirmPassword,
			String mobileNumber, String address, String gender, LocalDate dateOfBirth, String profileSummary,
			String highestEducationQualification, String yearOfPassing, String collegeName, String skills,
			int yearsOfExperience, String resumeUrl, String githubProfileUrl, String profileImageUrl,
			String preferredJobLocation, String noticePeriod, Double currentCtc, Double expectedCtc,
			boolean profileComplete, LocalDateTime createdAt, LocalDateTime updatedAt) {
		super();
		this.id = id;
		this.fullName = fullName;
		this.email = email;
		this.password = password;
		this.confirmPassword = confirmPassword;
		this.mobileNumber = mobileNumber;
		this.address = address;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.profileSummary = profileSummary;
		this.highestEducationQualification = highestEducationQualification;
		this.yearOfPassing = yearOfPassing;
		this.collegeName = collegeName;
		this.skills = skills;
		this.yearsOfExperience = yearsOfExperience;
		this.resumeUrl = resumeUrl;
		this.githubProfileUrl = githubProfileUrl;
		this.profileImageUrl = profileImageUrl;
		this.preferredJobLocation = preferredJobLocation;
		this.noticePeriod = noticePeriod;
		this.currentCtc = currentCtc;
		this.expectedCtc = expectedCtc;
		this.profileComplete = profileComplete;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * Parameterized constructor to initialize all fields of the JobSeeker entity.
	 */
	
}
